
BUILD_WRONG_POSITION="#BUILD_WRONG_POSITION"
BUILD_NO_TOWER_SELCTED="#BUILD_NO_TOWER_SELCTED"
NOT_ENOUGH_GOLD ="#NOT_ENOUGH_GOLD"
TECH_REACH_MAX_LEVEL="#TECH_REACH_MAX_LEVEL"
TECH_NEED_UNLOCK="#TECH_NEED_UNLOCK"
SPELL_CAN_NO_CAST_ON_POSITION="#SPELL_CAN_NO_CAST_ON_POSITION"
NOT_ENOUGH_TP="#NOT_ENOUGH_TP"
NOT_ENOUGH_CRYSTAL="#NOT_ENOUGH_CRYSTAL"
NOT_OWN_TARGET="#NOT_OWN_TARGET"
NOT_LEGAL_TARGET="#CanNotMerge"
OTHER_ABILITY_ON_COOLDOWN="#OTHER_ABILITY_ON_COOLDOWN"
function ErrorMsg(playerid,err)
	SendEventToPlayer(playerid,"ErrorMsg",{err=err})
end
